### ISSUE TITLE
How did you add scp/rsync support?

### ISSUE THREAD

**Issue by josegonzalez** [moul/sshportal#112]
I'm implementing a [simple ssh server](https://github.com/josegonzalez/ssh-github) on top of gliderlabs/ssh and realized it doesn't properly support scp/rsync. Do you have any tips/pointers as to how I might add that to my server? It's not clear from your codebase how you support it, or I'd look at that :)

**Comment by moul** [comment]
Hi @josegonzalez,

The way I did it is special: I just manage the authentication then create a pipe between the base client and the target server, this way, I don't have to manage each ssh subsystem or features by myself :)

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
