### ISSUE TITLE
moul.io is no more available

### ISSUE THREAD

**Issue by ilyaevseev** [moul/sshportal#115]
All import references to moul.io seems wrong.

Quick fix:
```
grep --include='*.go' -lR '"moul.io/sshportal/pkg/' . ~/go/src/ |
  xargs -r sed -i 's,moul.io/sshportal/pkg/,github.com/moul/sshportal/pkg/,g'
```

**Comment by ilyaevseev** [comment]
And quick fix for dependencies:
```
grep --include='*.go' -lR '"github.com/docker/docker/' . ~/go/src/ |
  xargs -r sed -i 's,github.com/docker/docker/,github.com/moby/moby/,g'
```

Both commands must be called in sshportal directory after "git clone", but before "go build" and after "go build" failures (before re-run it).

**Comment by moul** [comment]
ping me if the problem happens (again ?)

thank you
