### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by Yoda-BZH** [moul/sshportal#125]
Hello,

Can you provide a Debian package, or the necessary files to create one ?

Thank you !
Regards,
Yoda-BZH

**Comment by aderumier** [comment]
Hi,
I'm currently looking to make a .deb,  I'll try to send deb-src when it'll be done.

building is pretty easy: (note that you need recent golang, debian buster minimum)

mkdir sshportal
cd sshportal
export GOPATH=~/sshportal/
go get -u moul.io/sshportal
cd src/moul.io/sshportal/
make

then, the sshportal binary in generated in
~/sshportal/bin/

**Comment by Yoda-BZH** [comment]
I've been able to compile it with debian stretch using golang from stretch-backports (and @zeylos 's fix in #99 )

**Comment by TribalTux** [comment]
Hi,

I'm waiting too the Debian Package.

Thanks

**Comment by moul** [comment]
I will use goreleaser for the v2 (#v2), it supports creating .deb out of the box :)
