### ISSUE TITLE
Non-interactive ssh sessions error

### ISSUE THREAD

**Issue by bergo** [moul/sshportal#127]
**What happened**:
When we are running commands in non-interactive sessions against a server, the command exits with status -1 and without any output.

**What you expected to happen**:
The commands should run and produce some output.

**How to reproduce it (as minimally and precisely as possible)**:
Running the command 
`ssh $SSHPORTAL_HOST -p $SSHPORTAL_PORT -l $TARGET_HOST "<<cmd here>>"` in terminal works, but running the same e.g. inside and CI chain or Docker-Container produces the error. No ssh-client option (-t, -tt, ..) or forcing to run as interactive session still works. 
The server-session log file lists the requested command, but without any output. 

**Anything else we need to know?**:
The Log says "Error: rch closed the connection"

**Environment**:
OS Type: linux
OS Architecture: amd64
Go routines: 35
Go version (build): go1.12.1
Uptime: 49h40m44.268702385s
User ID: 1
User email: admin@localhost
Version: 1.9.0+dev
GIT SHA: 883bad2ee54557a6bc7a050242123f253dfad4c3
GIT Branch: master
GIT Tag: v1.9.0-33-g883bad2

**Comment by bergo** [comment]
Hi, 
is there nobody who uses SSHPortal with non interactive sessions like in CI/CD connections and can help?  It still fails in current version.

**Comment by moul** [comment]
@bergo thanks to @jrrdev, your issue should now be fixed :)

**Comment by bergo** [comment]
Works great, thx a lot to @jrrdev
