### ISSUE TITLE
docker password 

### ISSUE THREAD

**Issue by majestic1488** [moul/sshportal#128]
Hi!
I run the docker container as per instructions.
docker run -p 2222: 2222 -d --name = sshportal -v "$ (pwd): $ (pwd)" -w "$ (pwd)" moul / sshportal: v1.9.0

I looked through the logs through
docker logs -f sshportal

Found there administrator invite token.

When connected using
ssh localhost -p 2222 -l [invite token]

Output:

The authenticity of host '[localhost]: 2222 ([:: 1]: 2222)' can't be established.
RSA key fingerprint is SHA256: J3XonjHWFoMaFTeNIqhbSFmdbvVa4Yyy12wtuCYvsZs.
Are you sure you want to continue connecting (yes / no)? yes
Warning: Permanently added '[localhost]: 2222' (RSA) to the list of known hosts.
invite: ERzPy8kOtbatlurd @ localhost's password:

Why does he ask for a password?

- sshportal --version sshportal version 1.9.0+dev
- install method docker

**Comment by fbarmentlo** [comment]
Experiencing the same, 
sshportal --version
sshportal version 1.10.0+dev

ssh localhost -p 2244 -l invite:fMi44x8YIGvm7eeT
The authenticity of host '[localhost]:2244 ([127.0.0.1]:2244)' can't be established.
RSA key fingerprint is SHA256:LqVQZg3YTdpZuNDKucHIrCX4KKhxy0QEU5TsE+9TIRU.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:2244' (RSA) to the list of known hosts.
invite:fMi44x8YIGvm7eeT@localhost's password:

Install method also docker
I changed the port mapping with -p 2244:2222 as 2222 isn't available on the host

**Comment by duhow** [comment]
Try using single quotes:
```ssh -p 2244 -l 'invite:fMi44x8YIGvm7eeT' localhost
```

**Comment by clp71s** [comment]
Encountered the same issue as the above two users. Further testing identified that this error occurs when the host you're connecting from does not have an SSH key set up (so it cannot communicate an SSH public key to sshportal).

Fix is to run:

ssh-keygen -t rsa

Or similar to generate a key pair for use prior to connecting to sshportal.

**Comment by fbarmentlo** [comment]
You're a life saver,that was indeed the solution!
Enter file in which to save the key (/home/frank/.ssh/id_rsa): /home/frank/.ssh/                                     sshportal
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in *snip*

user@hostname:~$ ssh invite:u08qDARx4IZ8Eb3d@192.168.0.1 -p 2244 -i .ssh/sshportal
Welcome admin!
Your key is now associated with the user "admin@localhost".
Connection to 192.168.5.7 closed.
user@hostname:~$ ssh admin@192.168.5.7 -p 2244 -i .ssh/sshportal

    __________ _____           __       __
   / __/ __/ // / _ \___  ____/ /____ _/ /
  _\ \_\ \/ _  / ___/ _ \/ __/ __/ _ '/ /
 /___/___/_//_/_/   \___/_/  \__/\_,_/_/

config>

**Comment by xakraz** [comment]
So, we can close the issue ?
