### ISSUE TITLE
request: user/group/permission configuration through conf files (yaml,json...)

### ISSUE THREAD

**Issue by aderumier** [moul/sshportal#129]
Hi,

I could be great to be able to do configuration through conf files (yaml,json ...),
to be able to push them with configuration management software (ansible,puppet,chef....)
maybe sync them to database (and keep the dynamic ssh invite key registration).

Currently we could generate mysql query, but if we apply them multiple time, we have duplicate entries on some tables. (don't remember exactly, but I think this is the case for permissions)

**Comment by welderpb** [comment]
Hi,

You can use:
   # ssh portal config backup
   # ssh portal config restore
functionality.

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
