### ISSUE TITLE
REMOTE HOST IDENTIFICATION CHANGES ON RESTART

### ISSUE THREAD

**Issue by Merith-TK** [moul/sshportal#151]
**What happened**:
I set up my bastion server to have my Home PC as the admin, for security reasons as im always on the go
I compiled `sshportal` on my phone using Termux and CGO (something the releases forgot to do was enable CGO)

But whenever `sshportal` starts up, it has a "new" HostKey like setup, meaning openssh client flips it shit and does this
```
$ ssh 192.168.0.102 -p 2222 -l admin
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
SHA256:urcV05tjdbXzQp7oserntsvKTHWdVKpKQlyFFBKnM0s.
Please contact your system administrator.
Add correct host key in /home/merith/.ssh/known_hosts to get rid of this message.
Offending RSA key in /home/merith/.ssh/known_hosts:7
RSA host key for [192.168.0.102]:2222 has changed and you have requested strict checking.
Host key verification failed.
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Starting from fresh install of termux

```
pkg install golang
git clone https://github.com/moul/sshportal
cd sshportal
rm go.mod
go mod init
CGO_ENABLED=1 go build
```
and attempt to use it normally, restarting it for example, to simulate server downtime

**Comment by moul** [comment]
Hi :wave:,

At startup, sshportal creates a new host key if the database does not exist; you need to persist the database if you want to keep the host key fixed and avoid this kind of warnings
