### ISSUE TITLE
git push to a remote serveur through sshportal fails

### ISSUE THREAD

**Issue by olc** [moul/sshportal#161]
Bug report

**What happened**: 
Pushing to git repository on a server behind `sshportal` always fails:
```
$ git push foo master
[master 8ae61e8] commit
 1 file changed, 1 insertion(+), 1 deletion(-)
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), 273 bytes | 273.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
fatal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
```

**How to reproduce it (as minimally and precisely as possible)**:

```
$ ssh foo@localhost -p 2222
$ git init --bare repo.git
$ logout

$ echo -e "Host localhost\n   Port 2222\n" >> ~/.ssh/config

# `cd` into a directory where a local git repo exists, then:
$ git add remote foo foo@localhost:repo.git
$ git push foo master
```

**Environment**:
- tested with `sshportal` version 1.10.0+dev and docker hub version
- OS : linux & osx
- install method : go & docker

Feel free to ask for any additional info. Thanks.

**Comment by AlexGluck** [comment]
Try 1.24 should be fixed.

**Comment by olc** [comment]
Hi! Sorry for the delay. I'll give a try asap. Thanks an lot!

**Comment by moul** [comment]
thank you @AlexGluck 👍 
@olc, I close this issue (doing a big cleanup), feel free to reopen if needed)
