### ISSUE TITLE
format of audit-logs

### ISSUE THREAD

**Issue by James9022** [moul/sshportal#164]
Hello,

how to read audit-logs in filesystem (dir log/). They are in strange binary format. What kind of tool i have to use to read them? Thank you.

example of broken log:

cat  /var/lib/sqllite/log/10.0.3.20-test-session-23-2020-03-02T17\:40\:25Z
        E]^▒▒6Last login: Mon Mar  2 17:11:25 2020 from 10.0.3.10

E]u5TEST [root@web1:~]#
E]^▒
E]^
E]^H▒▒ 20:40:29 up 52 days, 23:03,  1 user,  load average: 0.01, 0.02, 0.05
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     pts/0    10.0.3.10        20:40    4.00s  0.04s  0.00s w
E]^)▒5TEST [root@web1:~]# E]^▒eE]^
xE]^▒~iE]^ZtE]^

logout

**Environment**:
- sshportal --version: sshportal version 1.10.0+dev (972e232559d202bb00fafcaa8992fcb9bd04b3de)

- sshportal info:
config> info
debug mode (server): false
Hostname: b2b2f3cb6e41
CPUs: 2
Demo mode: false
DB Driver: sqlite3
DB Conn: ./sshportal.db
Bind Address: :2222
System Time: 2020-03-07T06:08:39.957100069Z
OS Type: linux
OS Architecture: amd64
Go routines: 17
Go version (build): go1.14
Uptime: 114h3m0.607351648s
User ID: 1
User email: admin@localhost
Version: 1.10.0+dev
GIT SHA: 972e232559d202bb00fafcaa8992fcb9bd04b3de
GIT Branch: master
GIT Tag: v1.12.1
config>

- version sshportal: v1.12.1

- OS: CentOS 7

- install method: docker

**Comment by moul** [comment]
Hi @James9022 thank you for this issue,

I just updated the README.md file with some details about the current format used to log sessions (see this commit: https://github.com/moul/sshportal/commit/b6aaf4d7cfc962c9a7f3ebd56f1edae02af61bdb).
As you can see this is a well-known format that comes with a bunch of tools	

Feel free to share any extra information you think useful by opening a PR or just share the info here :)

thank you!

**Comment by moul** [comment]
Closing, but does not hesitate to continue the discussion here, or open a new issue if the topic is different

**Comment by moul** [comment]
The format used to record sessions is `script`/`ttyrec` (https://github.com/moul/sshportal/commit/b6aaf4d7cfc962c9a7f3ebd56f1edae02af61bdb)

Here is a short list of available tools:
* `scriptreplay` (bundled with `script`)
* `ttyplay` (bundled with `ttyrec`)
* https://tty-player.chrismorgan.info/ (web viewer)

**Comment by moul** [comment]
@James9022 please reply on this issue if you have anything to add

**Comment by adm9000-3** [comment]
scriptreplay dont work on logs (scriptreplay: cannot open typescript: No such file or directory) but ttyplay doing job well! Thank you.

**Comment by moul** [comment]
thank you @adm9000-3, updated my last comment accordingly + I will add `ttyplay` in the README now :+1:
