### ISSUE TITLE
Format of audit-logs

### ISSUE THREAD

**Issue by adm9000-3** [moul/sshportal#165]
Hello, how i can to read audit-logs (directory log/)? They are in strange binary format and commands like less/more/cat unable to help me.

for example audit-logs looks like:

***
cat /var/lib/sqllite/log/10.0.3.20-test-session-23-2020-03-02T17\:40\:25Z
        E]^▒▒6Last login: Mon Mar  2 17:11:25 2020 from 10.0.1.15

E]u5TEST [root@web1:~]#
E]^▒
E]^
E]^H▒▒ 20:40:29 up 52 days, 23:03,  1 user,  load average: 0.01, 0.02, 0.05
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
root     pts/0    10.0.1.15        20:40    4.00s  0.04s  0.00s w
E]^)▒5TEST [root@web1:~]# E]^▒eE]^
xE]^▒~iE]^ZtE]^

logout
***

How to read them? Is there any kind of tool to read them?

**Environment**:
- sshportal --version: sshportal version 1.10.0+dev (972e232559d202bb00fafcaa8992fcb9bd04b3de)
- ssh sshportal info:
config> info
debug mode (server): false
Hostname: b2b2f3cb6e41
CPUs: 2
Demo mode: false
DB Driver: sqlite3
DB Conn: ./sshportal.db
Bind Address: :2222
System Time: 2020-03-09T16:13:25.665719666Z
OS Type: linux
OS Architecture: amd64
Go routines: 17
Go version (build): go1.14
Uptime: 172h7m46.315970775s
User ID: 1
User email: admin@localhost
Version: 1.10.0+dev
GIT SHA: 972e232559d202bb00fafcaa8992fcb9bd04b3de
GIT Branch: master
GIT Tag: v1.12.1
config>

- OS (e.g. from /etc/os-release):  CentOS Linux release 7.6.1810 (Core)
- install method (e.g. go/docker/brew/...): docker (https://hub.docker.com/r/moul/sshportal)

**Comment by moul** [comment]
Duplicates of #164

**Comment by weiqian** [comment]
#164 is broken,  Is there any kind of tool to read sshportal audit logs? Thanks!

**Comment by Net-Felix** [comment]
interested in this too
