### ISSUE TITLE
Logging only user commands to prevent rapid disk space utilization

### ISSUE THREAD

**Issue by adm9000-3** [moul/sshportal#166]
Hello,

can i to toggle off logging stdout of user to prevent rapid disk space utilization?

For example if i use Linux command 'cat' on a 1 GB logfile and reading him in console i receive 1 GB audit-log on sshportal host.
This feature allows you to quickly destroy the sshportal host.

Can I leave only user commands logging? (like 'history' command in Linux)
Can you add this option to sshportal please?

Thank you.

**Comment by moul** [comment]
Interesting idea, is there anyone else with an opinion on this?

**Comment by adm9000-3** [comment]
Is there any chance that the option will appear soon?

**Comment by moul** [comment]
I'm on it (#188)
