### ISSUE TITLE
Session.MaskedReqs is not part of gliderlabs/ssh?

### ISSUE THREAD

**Issue by alexanderturner** [moul/sshportal#17]
Having some issues building. Has this been added after the fact. The SHA in vendor.json doesn't appear to have it in the upstream repo. What do?

```       
./proxy.go:31: s.MaskedReqs undefined (type "github.com/moul/sshportal/vendor/github.com/gliderlabs/ssh".Session has no field or method MaskedReqs)
```

**Comment by moul** [comment]
Hi @alexanderturner,

As you caught it, I'm not using an official release of `gliderlabs/ssh` (see https://github.com/gliderlabs/ssh/issues/47); as soon as an official way of handling `MaskedReqs` will be chosen by maintainers, I will switch back to an unmodified version of the dependency

FYI, I cherry-picked a commit from https://github.com/arkan/bastion (84e8352338df3259d66fbf8b2c139087eb4ff6b8)

For now, I suggest you use the shipped `vendor` directory (should be automatic when using Docker-based build or Golang > 1.5)

**Comment by alexanderturner** [comment]
Awesome! Maybe pull the dep from vendor.json so it doesn't get pulled down
automatically by govendor? I can submit a PR if it helps.

**Comment by moul** [comment]
Yes, sounds good 👌 

Your PR is welcome :)

**Comment by alexanderturner** [comment]
@moul  FYI https://github.com/moul/sshportal/pull/18
