### ISSUE TITLE
Create user with password

### ISSUE THREAD

**Issue by eshanaswar** [moul/sshportal#175]
How to create/invite a new user with password instead of private key ?

Also is there a documentation which can explain all the functions. Currently it is confusing to understand from the README file.

**Comment by jeanlouisferey** [comment]
I think it is not possible to authenticate a user with a password instead of a key pair.

And about documentation, you can find some help through https://github.com/moul/sshportal#features-and-limitations and particularly https://github.com/moul/sshportal#shell-commands
