### ISSUE TITLE
versions of go to use the package url

### ISSUE THREAD

**Issue by sabban** [moul/sshportal#37]
There's a small issue that we should care about:
https://github.com/moul/sshportal/blob/9cc09b320d6114ad88f89c7058b1bc93eb1722bb/db.go#L220-L224
https://github.com/moul/sshportal/blob/9cc09b320d6114ad88f89c7058b1bc93eb1722bb/db.go#L262-L266

These two lines give errors 
u.Port undefined (type *url.URL has no field or method Port)
u.Hostname undefined (type *url.URL has no field or method Port)

In fact these functions seem to be supported only since go 1.8. I can 
- Correct this to make it work with prior version
- Add some doc to point out golang version at least 1.8 is mandatory
Which solution do you prefer ?

**Comment by moul** [comment]
I think that it makes sense to support multiple versions of Golang for a library or when distributing the binary using sources

Sshportal is (mainly) distributed using Docker images, so I prefer to use the latest Golang functionalities and ask the contributors to use go >= 1.8, we need to update the README

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
