### ISSUE TITLE
build fail on MS Windows

### ISSUE THREAD

**Issue by Raerten** [moul/sshportal#42]
build fail on MS Windows
```
.\main.go:282:14: undefined: pty.Start
.\main.go:290:31: not enough arguments in call to syscall.Syscall
.\main.go:290:32: undefined: syscall.SYS_IOCTL
.\main.go:290:67: undefined: syscall.TIOCSWINSZ

Compilation finished with exit code 2
```
`go version go1.9.2 windows/amd64`, win 10 Pro

**Comment by moul** [comment]
Hi @Raerten 

I fixed your first problem (PTY) in this branch: https://github.com/moul/sshportal/compare/dev/moul/support-windows?expand=1

However, I now have a new building problem that seems to be already known by the community: https://github.com/mattn/go-sqlite3/issues/27

```console
$ GOOS=windows go build -v -i -o tmp .
github.com/moul/sshportal/vendor/github.com/mattn/go-sqlite3
# github.com/moul/sshportal/vendor/github.com/mattn/go-sqlite3
../../../go/src/github.com/moul/sshportal/vendor/github.com/mattn/go-sqlite3/sqlite3_go18.go:18:10: undefined: SQLiteConn
```

---

Is this an option for you to run sshportal in Linux, for instance using a VM or just "Docker for Windows" which supports Linux binary very nicely

**Comment by Raerten** [comment]
hi @moul 
I add PR that fix logs path and filename on Windows.
Now Windows build pass and it work's well.

**Comment by moul** [comment]
@Raerten can you update me about what's the current state on windows?

**Comment by Raerten** [comment]
@moul
I added PR #97. With this path the branch `dev/moul/support-windows` builds on Windows and it works well.
