### ISSUE TITLE
Reconnect to another server

### ISSUE THREAD

**Issue by shurco** [moul/sshportal#43]
Hello,
how to Reconnect to another server or selected server from list from admin console?

**Comment by moul** [comment]
Hi,

The admin console is currently designed to manage configuration only

After creating hosts using this console, you can connect to these hosts by using the "host key" as the SSH username, basically in this order:

1. `ssh admin@sshportal host create toto.com`: create a `toto.com` host with `toto` as key
2. `ssh toto@sshportal`: connect to toto through sshportal

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
