### ISSUE TITLE
bug with myqsl driver and hostgroup management

### ISSUE THREAD

**Issue by sabban** [moul/sshportal#45]
**What happened**:
When trying to assign an host to an hostgroup without unassigning from another hostgroup I get 
`error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '))' at line 1`

**What you expected to happen**:
I expected the host being added to a new hostgroup. It might be worth mentioning it would have result in havinge this host to two hostgroups

**How to reproduce it (as minimally and precisely as possible):
`host update  --assign-group=3 superhost`

**Anything else we need to know?**:
The problem seems to be located at https://github.com/moul/sshportal/blob/7c4aab34ed20f435be594105a6e8de47ade85abf/shell.go#L901
where append and delete are provided even if they are empty. I can provide some patch if needed, but I would like to discuss it before.

**Comment by maus007** [comment]
Hello 
What patch ? Have same problem

**Comment by sabban** [comment]
I have a fix for this in my branch/repo. But I do not know if this can make in master and I do not want to maintain a fork for this.

**Comment by moul** [comment]
Hi, sorry for the silent delay,

This is fixed with #49, basically tested in integration and merged in master

Thank for your report and help
