### ISSUE TITLE
User key create freeze

### ISSUE THREAD

**Issue by maus007** [moul/sshportal#46]
Hello 
When i try create user key console freeze on input fileld but server work
In this help only restart server 
Any ideas ?

**Comment by moul** [comment]
Hi @maus007 

I need a little bit more context, which are you running, which one is freezing?

**Comment by jafd** [comment]
The issue is as follows:
```
admin> userkey create 12
Enter key:
```
after which no input is accepted at all, and I need to kill the terminal session (because Ctrl-C stops working either). This prevents me from adding additional keys to my user account.

I have tried using the command like this:
```
echo "ssh-rsa XXXXXXXXXxxxx..." | ssh admin@portal userkey create 12
```
the output was:
```
error: Key: non zero value required;AuthorizedKey: non zero value required;
```

**Comment by cnf** [comment]
I am running into the same issue.

in docker
```
config> version          
1.8.0+dev
```
