### ISSUE TITLE
arm64 Docker image?

### ISSUE THREAD

**Issue by macourteau** [moul/sshportal#481]
### Actual Result / Problem

I'd like to run `sshportal` with Docker on a Raspberry Pi (though this would also apply to running this on a Mac, e.g. an Apple Silicon Mac Mini, or other ARM-based computers). There's only an amd64 image available, so it doesn't start up.

### Expected Result / Suggestion

It would be great if the published images also included an arm64 image to run natively on ARM machines.

**Comment by libvoid** [comment]
Hello,

This project is no longer maintained and lacks security updates. Honestly, you should consider choosing another SSH bastion :

- https://github.com/warp-tech/warpgate (seems promising but is only maintained by 1 person)
- https://github.com/gravitational/teleport (backed by a company)

If you really need to use sshportal, you may take a look [at our fork](https://github.com/alterway/sshportal) which provides `arm64` builds, is up to date and includes multiple security improvements / fixes. However keep in mind that our fork is on MAINTENANCE mode and only security issues and major bugs will be fixed. We do not plan to add or accept new features.

**Comment by macourteau** [comment]
Got it, thanks for the info. I'll look into all of these.
