### ISSUE TITLE
no support for ssh -D (SOCKS5)

### ISSUE THREAD

**Issue by cnf** [moul/sshportal#51]
**What happened**:
I opened a connection with `ssh somehost@portsl -D 3128` and tried using that port as a SOCKS proxy. This works fine if I do an `ssh someuser@somehost -D 3128`, but going through sshportal, that connection doesn't seem to get forwarded.

**What you expected to happen**:
For there to be an SOCKS5 capable connection.

**How to reproduce it (as minimally and precisely as possible)**:
Set up sshportal as normal, run `ssh host@portal -D 3128`, and point your browser to `127.0.0.1:3128` as a SOCKS5 proxy

**Anything else we need to know?**:
```
config> info
Debug mode (server): false
Hostname: remote-access-sshportal-1
CPUs: 1
Demo mode: false
DB Driver: sqlite3
DB Conn: ./sshportal.db
Bind Address: :2222
System Time: 2018-03-04T16:35:17.452370294Z
OS Type: linux
OS Architecture: amd64
Go routines: 45
Go version (build): go1.9.2
Uptime: 17m39.569968326s
User ID: 1
User email: admin@sshportal
Version: 1.7.1
GIT SHA: 2555c478b484c6b420c586c2c2a53b22445e3f7f
GIT Branch: HEAD
GIT Tag: v1.7.1
```

**Comment by cnf** [comment]
just tested with :latest on docker hub, and it is the same.

**Comment by moul** [comment]
Should be fixed now

Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
