### ISSUE TITLE
Running commands on hosts sometimes doesn't return output

### ISSUE THREAD

**Issue by jle64** [moul/sshportal#55]
**What happened**:
1) Running a command such as `ssh somehost@sshportal hostname` will sometimes return the command out put and sometimes not.

2) Piping something to a command input such as :
```
echo "print('test')" | ssh somehost@sshportal '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
```
seems to never return a result.

**What you expected to happen**:
Command output to show up.

**How to reproduce it (as minimally and precisely as possible)**:
Test with the aforementionned commands, see if you get a result.

**Anything else we need to know?**:
Running Ansible through sshportal doesn't work and due to the way it uses python I suspect this is related to the fact the second command I gave as example doesn't work.

**Environment**:
debug mode (server): false
Demo mode: false
DB Driver: mysql
Bind Address: :2222
OS Type: linux
OS Architecture: amd64
Go routines: 11
Go version (build): go1.9.4
Version: 1.7.1+dev
GIT SHA: 47a6fc9906a7be6666088e9f50fc6102fe94b55a
GIT Branch: dont_crash_on_missing_user
GIT Tag: v1.7.1-41-g47a6fc9

install method : docker build
OS : debian 9

**Comment by Yoda-BZH** [comment]
any update on this issue ?

**Comment by moul** [comment]
@Yoda-BZH @jle64 thanks to @jrrdev, your issue should now be fixed :)
