### ISSUE TITLE
Connection timeout handling for unavailable hosts

### ISSUE THREAD

**Issue by kreanda** [moul/sshportal#56]
**What happened**:

When the host you are  trying to connect is unavailable for some reason, sshportal is trying to connect infinitely, because Timeout field in gossh client configuration is equal to 0 by default. So client has endlessly frozen session.

**What you expected to happen**:

It would be great to have some (configurable) timeout value for outgoing connections in gossh client config (as a global option maybe). So, if some host is unavailable, client connection is closed by portal. 

**How to reproduce it (as minimally and precisely as possible)**:

To reproduce, just add some unavailable host and try to connect to it via portal. The host is unavailable, but ssh connection to portal is live and does nothing.

**Anything else we need to know?**:

To really close the connection, you need to add missing lch.Close() after error check in ChannelHandler:

        rconn, err := gossh.Dial("tcp", config.Addr, config.ClientConfig)
        if err != nil {
                lch.Close() // close client connection
                return err
        }

BTW, thanks for great tool, trying to use it internally in medium-sized web shop for interactive shells and afuse+sshfs mounted file systems.

**Comment by cchris-org** [comment]
Yes, timeout is a must have because its not possible to stop ssh client by ctrl-c during establish connection. You have to kill ssh client or restart sshportal :(

**Comment by moul** [comment]
Is it a problem if instead of implementing a timeout feature, I just make it possible to run ctrl-c during the connecting phase?

**Comment by kreanda** [comment]
I think it's not a good idea, because there are possible non-interactive use cases. For instance, we are (quite successfully) use patched sshportal to implement automatic mount of ssh-accessible resources via samba+afuse+sshfs. If a project is unavailable, it's ok to break connection on timeout, but it becomes   a problem if a connection just hangs.

**Comment by cchris-org** [comment]
I use sshportal for containers (lxc, docker) and it works well :).  But if a container is offline and a user want connect?. In this case ctrl-c could be useful for interactive sessions during the connecting phase.
Maybe an option to enable/disable ctrl-c?

**Comment by moul** [comment]
I plan to make the <kbd>ctrl</kbd>+<kbd>C</kbd> behavior the same in sshportal as in standard ssh: if a connection is taking too long, you should not have to kill the ssh process or stop sshportal.

Additionally, I'm thinking about @kreanda's specific case: non-interactive timeouts, I'm still not sure if we should have a native timeout that automatically closes the connection, or if non-interactive handling timeout should be addressed by an external tool?

**Comment by kreanda** [comment]
"non-interactive handling timeout should be addressed by an external tool" — it can easily be addressed for a connection timeout between a client and sshportal, but it's more complicated (or just impossible) if the problem is between sshportal and an external host. No way to solve it for sshfs, for instance.

**Comment by moul** [comment]
Fixed by #123

**Comment by hacko2** [comment]
@moul keeps getting stuck without a timeout and unable to do ctrl + c, use the latest version of docker hub.
