### ISSUE TITLE
Add global option to disable session logs.

### ISSUE THREAD

**Issue by kreanda** [moul/sshportal#57]
**What happened**:

When using sshportal, for instance, for sftp connections, session logs contains all data sent. So if you send large volumes of data, you have all of them written to session logs on portal server, so after some time the disk is full and portal stops working.

**What you expected to happen**:

IMO, session logs are rather impractical, because you can attack portal server with simple shell script producing lots of data, or by simply sending large files with sftp. So, it would be good idea to add global option to disable logs (and disable logs by default). 

Using nullfs with the current version as a temporarily hack.

**Comment by duhow** [comment]
Same here, my drive was full for two times.
@kreanda how do you set the nullfs?

**Comment by moul** [comment]
I'm on it (#188)
