### ISSUE TITLE
Store correct session duration

### ISSUE THREAD

**Issue by nymous** [moul/sshportal#62]
**What happened**:

When connecting to a host through sshportal, an entry is created in the `sessions` table. But all connections are shown as "Closed" immediately, and the `stopped_at` column is set to the same value as the `created_at`.

**What you expected to happen**:

sshportal saves the timestamp when the connection closes.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup sshportal with a user and a host
1. Connect to the host
1. In another terminal, run `session ls` in sshportal
1. Session is marked as "Closed", with a 1s duration

**Environment**:
- `sshportal --version`: sshportal version 1.8.0+dev ()
- `sshportal info`:
```
debug mode (server): false
Hostname: bastion
CPUs: 4
Demo mode: false
DB Driver: mysql
DB Conn: REDACTED@tcp(localhost:3306)/sshportal?charset=utf8&parseTime=true&loc=Local
Bind Address: :2222
System Time: 2018-06-26T14:22:35.351678631Z
OS Type: linux
OS Architecture: amd64
Go routines: 2275
Go version (build): go1.8.3
Uptime: 1302h33m53.669240829s
User ID: 4
User email: REDACTED
Version: 1.8.0+dev
GIT SHA:
GIT Branch:
GIT Tag:
```
- OS: CentOS 7.4.1708
- install method: go
- installed with a MySQL DB to store data

**Comment by moul** [comment]
fixed by #75
