### ISSUE TITLE
Security/Production Readiness

### ISSUE THREAD

**Issue by Immortalin** [moul/sshportal#64]
Hi! Thanks so much for building this, I have been looking for something like this for a long time. Is this production ready? E.g. if I let students (assuming hostile users) SSH into various servers hosting Jupyter notebooks, is there any possibility that the bastion server may be compromised etc.? If it get compromised, is there any risk for other users to be MITMed?

**Comment by Immortalin** [comment]
@moul thanks for your comprehensive reply! I am using it as bastion for Kubernetes cluster, and after students sign up, the web front end will automatically provision a server and create an account through the bastion, is this a correct use case?

**Comment by moul** [comment]
Yes, definitely, I'm also using it in equivalent workflows

**Comment by kreanda** [comment]
We use patched version to implement single access for our developers to hundreds of client hosting servers. Besides interactive ssh sessions, we implemented non interactive automatic mounting of remote filesystems using afuse, sshfs and samba. There are some glitches (connection timeouts — solved with a patch, and we have to disable logs with nullfs), but in general it is very useful lighweight tool with well designed UX. Works pretty stable (knock on wood). Great work!

**Comment by Immortalin** [comment]
@kreanda any plans to send a pull?
