### ISSUE TITLE
Race Conditions/Thread Safety/Automation question/Host key clarification

### ISSUE THREAD

**Issue by Immortalin** [moul/sshportal#65]
Hi! Can SSHportal be called simultaneously by multiple programs i.e. through an API? What's the recommended way of automating user, ACL creation etc.? Direct database edits? Automated ssh shell input scripting i.e. Python paramiko? 

Also, just to clarify, what does `Host Keys verifications shared across users` mean? Does that mean it will record the identity of the remote server once (trust on first use) and this shall be recorded for all SSHPortal users?

**Comment by moul** [comment]
Can you give more details?

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
