### ISSUE TITLE
session ls fails with "Error 1390: Prepared statement contains too many placeholders"

### ISSUE THREAD

**Issue by jle64** [moul/sshportal#71]
**What happened**:
Doing a `session ls` results in an error message :

```
config> session ls
error: Error 1390: Prepared statement contains too many placeholders
```

**What you expected to happen**:

Sessions should be listed.

**How to reproduce it (as minimally and precisely as possible)**:
Doing a `session ls` while having many sessions in the database (90000+ in our case) and using MySQL.

**Comment by moul** [comment]
fixed by #76
