### ISSUE TITLE
sessions are marked as closed even when they are open

### ISSUE THREAD

**Issue by jle64** [moul/sshportal#72]
**What happened**:
When doing a `session ls`, sessions are all shown as closed, even those that are currently open.

**What you expected to happen**:
Open session sshould be marked as open.

**How to reproduce it (as minimally and precisely as possible)**:
Open a session to a host and in parallel do a `session ls` on the sshportal cli. The session will be seen as closed even though it is open

**Comment by moul** [comment]
fixed by #75
