### ISSUE TITLE
Possibility of not logging file content when using scp/rsync

### ISSUE THREAD

**Issue by jle64** [moul/sshportal#73]
Currently, a file copy done through sshportal using utilities such as scp or rsync logs the file content.

(at least when pulling a file, oddly enough the file content doesn't seem to be logged when pushing a file)

If many files or big files are being copied this can quickly lead to a huge usage of storage space.

It would be great if there was a way to detect sessions that are scp/rsync/etc and avoid logging their content.

**Comment by moul** [comment]
working on something related in #188

**Comment by jle64** [comment]
Sorry didn't notice the feedback needed comment. I tested and this is perfect as far as I'm concerned, thanks !
