### ISSUE TITLE
error: unknown ssh key when re-connecting after ~5 minutes

### ISSUE THREAD

**Issue by zeylos** [moul/sshportal#77]
Hi,

**What happened**:
When trying to connect to the admin cli after ~5min of inactivity : 
`error: unknown ssh key`
I also had errors where I could connect but he couldn't find informations in the database, like usergroups.

**What you expected to happen**:
Connecting successfully

**How to reproduce it (as minimally and precisely as possible)**:
Connect as admin, disconnect, wait for 5 minutes, connect again.

**Anything else we need to know?**:
Looking at the logs i found this
```
Nov 12 16:10:26 sshportal[1933]: [mysql] 2018/11/12 16:10:26 packets.go:36: unexpected EOF
Nov 12 16:10:30 sshportal[1933]: [mysql] 2018/11/12 16:10:30 connection.go:372: invalid connection
```
Looks like it's related to this ? https://github.com/go-sql-driver/mysql/issues/674

**Environment**:
- sshportal --version
```
/usr/local/go/bin/sshportal --version            
sshportal version 1.8.0+dev ()   
```
- ssh sshportal info
```                                                                                                                                 
debug mode (server): false                                                                                                                                   
Hostname: **
CPUs: 2
Demo mode: false
DB Driver: mysql
DB Conn: sshportal:****@tcp(127.0.0.1:3306)/sshportal?charset=utf8&parseTime=true&loc=Local
Bind Address: :2222
System Time: 2018-11-12T16:34:30.907853325+01:00
OS Type: linux
OS Architecture: amd64
Go routines: 96
Go version (build): go1.10.3
Uptime: 73h40m41.205006889s
User ID: 1
User email: root@localhost
Version: 1.8.0+dev
GIT SHA: 
GIT Branch: 
GIT Tag: 
```
- OS (e.g. from /etc/os-release): 
```
cat /etc/debian_version                                                                                                                   
9.5                
```
- install method (e.g. go/docker/brew/...): `go`

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
