### ISSUE TITLE
Go get broken for 1.9

### ISSUE THREAD

**Issue by zeylos** [moul/sshportal#99]
Hi,

go get looks broken after last patches ?

**What happened**:
```
go get -u moul.io/sshportal
package github.com/moby/moby/pkg/namesgenerator: code in directory /usr/local/go/src/github.com/moby/moby/pkg/namesgenerator expects import "github.com/docker/docker/pkg/namesgenerator"
```
**What you expected to happen**:
installing successfully

**How to reproduce it (as minimally and precisely as possible)**:
`go get -u moul.io/sshportal`

**Anything else we need to know?**:
~EDIT: `sed -ie "17s/moby/docker/g" src/moul.io/sshportal/shell.go` seems to be working~
EDIT2: `sed -ie "18s/moby/docker/g" src/moul.io/sshportal/pkg/bastion/shell.go` seems to be working

**Environment**:
- sshportal --version : 
```
/usr/local/go/bin/sshportal --version            
sshportal version 1.8.0+dev ()   
```

**Comment by Yoda-BZH** [comment]
same here, tested with go 1.11 and 1.12, using debian/testing

**Comment by Yoda-BZH** [comment]
> EDIT: sed -ie "17s/moby/docker/g" src/moul.io/sshportal/shell.go seems to be working
returns `No such file or directory.`

```
find src/moul.io/sshportal/ -name shell.go
src/moul.io/sshportal/pkg/bastion/shell.go
```

**Comment by zeylos** [comment]
Ah yea, forgot to update my issue, new fix-line is 
sed -ie "18s/moby/docker/g" src/moul.io/sshportal/pkg/bastion/shell.go

**Comment by Yoda-BZH** [comment]
Thank you !

**Comment by moul** [comment]
Closing the issue as I plan to work on the v2 of this project and I need to make some cleanup in the issues see #210
